name: Build and Test Gem

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        jruby-version: ["9.4", "10.0", "10.1"]
        java-version: ["21"]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java-version }}

      - name: Set up JRuby
        uses: ruby/setup-ruby@4c56a21280b36d862b5fc31348f463d60bdc55d5 # v1.301.0
        with:
          ruby-version: jruby-${{ matrix.jruby-version }}
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle install
          ./gradlew clean vendor

      - name: Build gem
        run: gem build logstash-integration-aws.gemspec
